# Generated by Django 5.2.8 on 2025-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('type', models.CharField(choices=[('WSPOLNOTA', 'Wspólnota mieszkaniowa'), ('SPOLDZIELNIA', 'Spółdzielnia'), ('FIRMA', 'Firma'), ('OSOBA', 'Osoba prywatna'), ('INNE', 'Inne')], default='FIRMA', max_length=20, verbose_name='Typ jednostki')),
                ('nip', models.CharField(blank=True, max_length=20, verbose_name='NIP')),
                ('regon', models.CharField(blank=True, max_length=20, verbose_name='REGON')),
                ('pesel', models.CharField(blank=True, max_length=11, verbose_name='PESEL')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Ulica i nr')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miejscowość')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
        ),
    ]
