# Generated by Django 5.2.8 on 2025-11-24 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa obiektu')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Ulica i nr')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miejscowość')),
                ('site_type', models.CharField(choices=[('MIESZKALNY', 'Mieszkalny'), ('BIUROWY', 'Biurowy'), ('USLUGOWY', 'Usługowy'), ('MAGAZYNOWY', 'Magazynowy'), ('INNY', 'Inny')], default='MIESZKALNY', max_length=20, verbose_name='Typ obiektu')),
                ('access_info', models.TextField(blank=True, help_text='Np. gdzie są klucze, kody, portiernia, sposób wejścia.', verbose_name='Informacje o dostępie')),
                ('technical_notes', models.TextField(blank=True, help_text='Np. lokalizacja szaf, central, uwagi dla serwisanta.', verbose_name='Notatki techniczne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.entity', verbose_name='Jednostka')),
            ],
        ),
    ]
