# Generated by Django 5.2.8 on 2025-11-24 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nazwisko')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=255, verbose_name='E-mail')),
                ('company', models.CharField(blank=True, help_text='Np. nazwa firmy zarządcy, jeśli dotyczy.', max_length=255, verbose_name='Firma / organizacja')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ZARZADCA', 'Zarządca'), ('ADMINISTRATOR', 'Administrator'), ('WLASCICIEL', 'Właściciel'), ('KONTAKT_AWARIE', 'Kontakt ds. awarii'), ('KONTAKT_ROZLICZENIA', 'Kontakt ds. rozliczeń'), ('INNY', 'Inna rola')], default='ZARZADCA', max_length=30, verbose_name='Rola')),
                ('is_default_for_notifications', models.BooleanField(default=False, help_text='Domyślny adresat protokołów / informacji.', verbose_name='Domyślny do powiadomień')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_links', to='core.contact', verbose_name='Kontakt')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_contacts', to='core.site', verbose_name='Obiekt')),
            ],
            options={
                'verbose_name': 'Powiązanie obiektu z kontaktem',
                'verbose_name_plural': 'Powiązania obiektów z kontaktami',
                'unique_together': {('site', 'contact', 'role')},
            },
        ),
    ]
