# Generated by Django 5.2.8 on 2025-11-24 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact_sitecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(choices=[('CCTV', 'CCTV'), ('SSP', 'System Sygnalizacji Pożaru'), ('ALARM', 'System alarmowy'), ('ODDYM', 'Oddymianie'), ('KD', 'Kontrola dostępu'), ('DOMOFON', 'Domofon'), ('VIDEODOMOFON', 'Wideodomofon'), ('TVSAT', 'TV naziemna / SAT'), ('SWIATLOWOD', 'Światłowód'), ('INNY', 'Inny system')], default='CCTV', max_length=20, verbose_name='Typ systemu')),
                ('name', models.CharField(help_text="Np. 'CCTV garaż + wejścia', 'SSP budynek A+B'.", max_length=255, verbose_name='Nazwa / opis systemu')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Producent')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model / centrala / rejestrator')),
                ('commissioning_date', models.DateField(blank=True, null=True, verbose_name='Data uruchomienia')),
                ('last_modernization_date', models.DateField(blank=True, null=True, verbose_name='Data ostatniej modernizacji')),
                ('in_service_contract', models.BooleanField(default=False, help_text='Czy system jest objęty stałą umową serwisową.', verbose_name='W umowie serwisowej')),
                ('location_info', models.TextField(blank=True, help_text='Np. gdzie jest centrala, rejestrator, szafy, przyciski ROP itp.', verbose_name='Lokalizacja urządzeń')),
                ('access_data', models.TextField(blank=True, help_text='Dane wrażliwe – kody, loginy, hasła do urządzeń.', verbose_name='Hasła / kody / dane dostępowe')),
                ('procedures', models.TextField(blank=True, help_text='Opis procedur testowych, uruchomieniowych, resetów itp.', verbose_name='Procedury testowe / serwisowe')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki techniczne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.site', verbose_name='Obiekt')),
            ],
        ),
    ]
