# Generated by Django 5.2.8 on 2025-11-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(help_text='Nazwa robocza, używana na co dzień.', max_length=255, verbose_name='Nazwa skrócona')),
                ('full_name', models.CharField(help_text='Pełna nazwa według danych rejestrowych.', max_length=255, verbose_name='Pełna nazwa')),
                ('nip', models.CharField(blank=True, max_length=20, verbose_name='NIP')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Ulica i nr')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Kod pocztowy')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miejscowość')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
            ],
            options={
                'verbose_name': 'Zarządca',
                'verbose_name_plural': 'Zarządcy',
            },
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Osoba kontaktowa', 'verbose_name_plural': 'Osoby kontaktowe'},
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': 'Dane fakturowe', 'verbose_name_plural': 'Dane fakturowe'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Obiekt', 'verbose_name_plural': 'Obiekty'},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'verbose_name': 'System na obiekcie', 'verbose_name_plural': 'Systemy na obiektach'},
        ),
    ]
