# Generated by Django 5.2.8 on 2025-11-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_manager_alter_contact_options_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='google_maps_url',
            field=models.URLField(blank=True, help_text='Wklej link do pinezki/obiektu z Google Maps, aby łatwo go otworzyć.', max_length=500, verbose_name='Link do Google Maps'),
        ),
        migrations.AddField(
            model_name='site',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Firma zarządzająca tym obiektem (opcjonalnie).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='core.manager', verbose_name='Zarządca'),
        ),
        migrations.AlterField(
            model_name='site',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='core.entity', verbose_name='Dane fakturowe'),
        ),
    ]
