# Generated by Django 5.2.8 on 2025-11-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_site_google_maps_url_site_manager_alter_site_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
        migrations.AddField(
            model_name='contact',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Jeśli osoba jest pracownikiem konkretnego zarządcy.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.manager', verbose_name='Zarządca'),
        ),
    ]
