# Generated by Django 5.2.8 on 2025-11-25 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_contact_company_contact_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('NOWY_MONTAZ', 'Nowy montaż'), ('MODERNIZACJA', 'Modernizacja'), ('ROZBUDOWA', 'Rozbudowa'), ('INNE', 'Inne')], default='NOWY_MONTAZ', max_length=20, verbose_name='Typ robót')),
                ('title', models.CharField(help_text="Krótka nazwa, np. 'Montaż CCTV garaż P25–33'.", max_length=255, verbose_name='Nazwa robót')),
                ('description', models.TextField(blank=True, help_text='Szczegółowy zakres prac zgodnie z ofertą/umową.', verbose_name='Opis / zakres robót')),
                ('status', models.CharField(choices=[('PLANOWANA', 'Planowana'), ('W_REALIZACJI', 'W realizacji'), ('ZAWIESZONA', 'Zawieszona'), ('ZAKONCZONA', 'Zakończona'), ('ANULOWANA', 'Anulowana')], default='PLANOWANA', max_length=20, verbose_name='Status robót')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Planowany start')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Planowane zakończenie')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='Rzeczywisty start')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Rzeczywiste zakończenie')),
                ('offer_number', models.CharField(blank=True, max_length=100, verbose_name='Numer oferty')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Numer umowy / zlecenia')),
                ('notes', models.TextField(blank=True, verbose_name='Notatki wewnętrzne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('entity', models.ForeignKey(blank=True, help_text='Jeśli inne niż domyślne dane fakturowe obiektu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.entity', verbose_name='Dane fakturowe')),
                ('main_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_as_main_contact', to='core.contact', verbose_name='Główna osoba kontaktowa')),
                ('manager', models.ForeignKey(blank=True, help_text='Jeśli inny niż domyślny zarządca obiektu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='core.manager', verbose_name='Zarządca')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='core.site', verbose_name='Obiekt')),
            ],
            options={
                'verbose_name': 'Robota',
                'verbose_name_plural': 'Roboty',
                'ordering': ['-created_at'],
            },
        ),
    ]
