# Generated by Django 5.2.8 on 2025-11-25 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('MAINTENANCE', 'Przegląd okresowy'), ('SERVICE', 'Serwis awaryjny'), ('JOB', 'Robota / montaż (wyjazd)'), ('OTHER', 'Inne')], default='SERVICE', max_length=20, verbose_name='Typ zlecenia')),
                ('title', models.CharField(help_text="Np. 'Awaria domofonu kl. B', 'Przegląd SSP Q1/2025'.", max_length=255, verbose_name='Tytuł / krótki opis')),
                ('description', models.TextField(blank=True, verbose_name='Opis zgłoszenia / zakres prac')),
                ('internal_notes', models.TextField(blank=True, verbose_name='Notatki wewnętrzne')),
                ('status', models.CharField(choices=[('NEW', 'Nowe'), ('ASSIGNED', 'Przydzielone'), ('IN_PROGRESS', 'W realizacji'), ('CLOSED', 'Zamknięte')], default='NEW', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normalny'), ('HIGH', 'Wysoki'), ('CRITICAL', 'Krytyczny')], default='NORMAL', max_length=20, verbose_name='Priorytet')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Planowana data wizyty')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Data zamknięcia')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Przypisano do')),
                ('job', models.ForeignKey(blank=True, help_text='Jeśli zlecenie jest częścią konkretnej roboty (montaż/modernizacja).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.job', verbose_name='Robota')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_work_orders', to='core.contact', verbose_name='Zgłaszający (kontakt)')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='core.site', verbose_name='Obiekt')),
                ('system', models.ForeignKey(blank=True, help_text='Opcjonalnie: jeśli zlecenie dotyczy konkretnego systemu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='core.system', verbose_name='System')),
            ],
            options={
                'verbose_name': 'Zlecenie',
                'verbose_name_plural': 'Zlecenia',
                'ordering': ['-created_at'],
            },
        ),
    ]
