# Generated by Django 5.2.8 on 2025-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(blank=True, help_text="Np. 'CCTV garaż + wejścia', jeśli obiekt ma kilka systemów tego samego typu.", max_length=255, verbose_name='Opis systemu (opcjonalnie)'),
        ),
    ]
