# Generated by Django 5.2.8 on 2025-11-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_system_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='system',
        ),
        migrations.AddField(
            model_name='workorder',
            name='systems',
            field=models.ManyToManyField(blank=True, help_text='Jeśli zlecenie dotyczy konkretnych systemów na obiekcie, wybierz je tutaj.', related_name='work_orders', to='core.system', verbose_name='Systemy objęte zleceniem'),
        ),
    ]
