# Generated by Django 5.2.8 on 2025-11-25 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_workorder_system_workorder_systems'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text="Jeśli puste, numer zostanie nadany automatycznie w formacie 'PS 01-11-2025'.", max_length=20, verbose_name='Numer protokołu')),
                ('report_date', models.DateField(blank=True, null=True, verbose_name='Data protokołu')),
                ('service_mode', models.CharField(blank=True, choices=[('WARRANTY', 'Gwarancja'), ('CONTRACT', 'Umowa'), ('PAID', 'Płatny')], help_text='Gwarancja / Umowa / Płatny.', max_length=20, verbose_name='Tryb serwisu')),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Gotówka'), ('TRANSFER', 'Przelew'), ('CONTRACT', 'Zgodnie z umową')], max_length=20, verbose_name='Forma płatności')),
                ('requester_name', models.CharField(blank=True, help_text='Jeśli inna niż osoba kontaktowa w zleceniu.', max_length=255, verbose_name='Osoba zgłaszająca')),
                ('requester_phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon zgłaszającego')),
                ('description_before', models.TextField(blank=True, help_text='Jaką usterkę zgłoszono, jaki był stan systemu przed podjęciem prac.', verbose_name='Opis usterki / stan przed')),
                ('work_performed', models.TextField(blank=True, verbose_name='Opis wykonanych prac')),
                ('result', models.CharField(blank=True, choices=[('REPAIRED', 'Usterka usunięta'), ('TEMPORARY', 'Przywrócono pracę czasowo'), ('NOT_FIXED', 'Nie usunięto usterki'), ('INSPECTION_ONLY', 'Sprawdzenie / diagnostyka')], max_length=20, verbose_name='Wynik')),
                ('next_actions', models.TextField(blank=True, help_text='Np. konieczność wymiany elementów, ponowna wizyta, oferta.', verbose_name='Zalecenia / dalsze kroki')),
                ('technicians', models.CharField(blank=True, help_text='Nazwiska serwisantów (np. z dwoma osobnymi wierszami w szablonie wydruku).', max_length=255, verbose_name='Serwisanci')),
                ('invoice_data', models.TextField(blank=True, help_text='Jeśli trzeba wpisać ręcznie dane do faktury podane przez klienta.', verbose_name='Dane do faktury')),
                ('material_security', models.TextField(blank=True, help_text='Informacja o zabezpieczeniu materiału / sprzętu zgodnie z procedurą.', verbose_name='Zabezpieczenie materiału')),
                ('notes_internal', models.TextField(blank=True, help_text='Widoczne tylko wewnętrznie, nie drukują się na protokole dla klienta.', verbose_name='Notatki wewnętrzne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('work_order', models.OneToOneField(help_text='Zlecenie, którego dotyczy ten protokół (typu Serwis awaryjny).', on_delete=django.db.models.deletion.CASCADE, related_name='service_report', to='core.workorder', verbose_name='Zlecenie')),
            ],
            options={
                'verbose_name': 'Protokół serwisowy',
                'verbose_name_plural': 'Protokoły serwisowe',
            },
        ),
        migrations.CreateModel(
            name='ServiceReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Opis pozycji')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Ilość')),
                ('unit', models.CharField(choices=[('RBH', 'rbh'), ('SZT', 'szt.'), ('KM', 'km'), ('INNE', 'inne')], default='RBH', max_length=10, verbose_name='Jm')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cena jedn. netto')),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, help_text='Może być liczone ręcznie lub później na fakturze.', max_digits=10, null=True, verbose_name='Wartość netto')),
                ('order_index', models.PositiveIntegerField(default=0, help_text='Do sortowania pozycji na protokole.', verbose_name='Kolejność')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.servicereport', verbose_name='Protokół serwisowy')),
            ],
            options={
                'verbose_name': 'Pozycja protokołu serwisowego',
                'verbose_name_plural': 'Pozycje protokołu serwisowego',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
