# Generated by Django 5.2.8 on 2025-11-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_servicereport_servicereportitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereport',
            name='invoice_data',
        ),
        migrations.RemoveField(
            model_name='servicereport',
            name='material_security',
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='requester_name',
            field=models.CharField(blank=True, help_text='Kontakt do osoby zgłaszającej / zarządzającej obiektem.', max_length=255, verbose_name='Osoba zgłaszająca'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='requester_phone',
            field=models.CharField(blank=True, help_text='Telefon do osoby zgłaszającej / zarządzającej obiektem.', max_length=50, verbose_name='Telefon zgłaszającego'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='technicians',
            field=models.CharField(blank=True, help_text='Automatycznie uzupełniane na podstawie zlecenia (przypisanego pracownika).', max_length=255, verbose_name='Serwisanci'),
        ),
        migrations.AlterField(
            model_name='servicereportitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Może być liczone automatycznie jako ilość × cena jedn.', max_digits=10, null=True, verbose_name='Wartość netto'),
        ),
    ]
