# Generated by Django 5.2.8 on 2025-11-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_servicereport_invoice_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='planned_time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina od'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='planned_time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Godzina do'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='visit_type',
            field=models.CharField(choices=[('FLEXIBLE', 'W ciągu dnia'), ('WINDOW', 'Na przedział godzinowy')], default='FLEXIBLE', max_length=16, verbose_name='Rodzaj wizyty'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('SCHEDULED', 'Umówione'), ('IN_PROGRESS', 'W realizacji'), ('WAITING_FOR_DECISION', 'Czeka na decyzję klienta'), ('WAITING_FOR_PARTS', 'Czeka na materiał'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Odwołane')], default='NEW', max_length=32, verbose_name='Status'),
        ),
    ]
