# Generated by Django 5.2.8 on 2025-11-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_workorder_planned_time_from_and_more'),
    ]

    operations = [
    migrations.AddField(
        model_name='workorder',
        name='number',
        field=models.CharField(
            blank=True,
            null=True,
            max_length=32,
            unique=True,
            verbose_name='Numer zlecenia',
        ),
    ),
]

