# Generated by Django 5.2.8 on 2025-11-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_workorder_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='planned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Termin realizacji'),
        ),
    ]
