# Generated by Django 5.2.8 on 2025-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_workorder_planned_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='priority',
        ),
        migrations.AddField(
            model_name='servicereport',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Szkic'), ('FINAL', 'Zatwierdzony')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='number',
            field=models.CharField(blank=True, help_text='Jeśli puste, numer zostanie nadany automatycznie przy zatwierdzeniu (PS 01-MM-RRRR).', max_length=20, verbose_name='Numer protokołu'),
        ),
    ]
