# Generated by Django 5.2.8 on 2025-12-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_system_system_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='system_type',
            field=models.CharField(choices=[('CCTV', 'System CCTV'), ('SSP', 'System SSP'), ('ALARM', 'System SSWiN'), ('ODDYM', 'System Oddymiania'), ('KD', 'System Kontroli Dostępu'), ('DOMOFON', 'Domofon'), ('VIDEODOMOFON', 'System Video/Domofonowy'), ('TVSAT', 'System RTV/SAT'), ('SWIATLOWOD', 'Sieci LAN/OPTO'), ('INNY', 'Inny system')], default='CCTV', max_length=20, verbose_name='Typ systemu'),
        ),
    ]
