# Generated by Django 5.2.8 on 2025-12-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_system_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='maintenance_custom_months',
            field=models.CharField(blank=True, help_text="Lista miesięcy 1–12 rozdzielona przecinkami, np. '1,4,7,10'.", max_length=50, null=True, verbose_name='Miesiące przeglądów (CUSTOM)'),
        ),
        migrations.AddField(
            model_name='site',
            name='maintenance_frequency',
            field=models.CharField(choices=[('NONE', 'Brak stałych przeglądów'), ('MONTHLY', 'Co miesiąc'), ('QUARTERLY', 'Co kwartał'), ('SEMIANNUAL', '2x w roku'), ('CUSTOM', 'Wg wybranych miesięcy')], default='NONE', help_text='Określa schemat przeglądów okresowych na obiekcie.', max_length=15, verbose_name='Częstotliwość przeglądów'),
        ),
        migrations.AddField(
            model_name='site',
            name='maintenance_start_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], help_text='Używane dla schematów co miesiąc / kwartał / 2x w roku.', null=True, verbose_name='Miesiąc startowy przeglądów'),
        ),
    ]
