# Generated by Django 5.2.8 on 2025-12-04 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_site_maintenance_custom_months_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Numer w formacie KS {kolejny}/{MM}/{RRRR}.', max_length=50, unique=True, verbose_name='Numer protokołu')),
                ('sequence_number', models.PositiveIntegerField(blank=True, help_text='Numer porządkowy KS w danym roku.', null=True, verbose_name='Kolejny numer w roku')),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Miesiąc okresu przeglądu')),
                ('period_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rok okresu przeglądu')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data wykonania przeglądu')),
                ('next_period_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Miesiąc następnego przeglądu')),
                ('next_period_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Rok następnego przeglądu')),
                ('status', models.CharField(choices=[('OPEN', 'W edycji'), ('CLOSED', 'Zamknięty')], default='OPEN', max_length=16, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Zaktualizowano')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_protocols', to='core.site', verbose_name='Obiekt')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_protocol', to='core.workorder', verbose_name='Zlecenie przeglądu')),
            ],
            options={
                'verbose_name': 'Protokół konserwacji',
                'verbose_name_plural': 'Protokoły konserwacji',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(blank=True, help_text='Cache typu systemu (SSP, CCTV, SSWIN itp.) dla raportów.', max_length=32, verbose_name='Typ systemu')),
                ('header_name', models.CharField(help_text='Np. "System SSP", "System CCTV".', max_length=100, verbose_name='Nazwa sekcji')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Producent')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('location', models.CharField(blank=True, help_text='Np. portiernia, rozdzielnia, szafa RACK itp.', max_length=255, verbose_name='Lokalizacja')),
                ('section_result', models.CharField(blank=True, choices=[('OK', '✓ poprawny'), ('FAIL', 'X niepoprawny'), ('NOT_DONE', 'O niewykonany')], max_length=16, null=True, verbose_name='Wynik sekcji')),
                ('section_remarks', models.TextField(blank=True, help_text='Podsumowanie przeglądu dla całego systemu w tej sekcji.', verbose_name='Uwagi (podsumowanie sekcji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność sekcji')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.maintenanceprotocol', verbose_name='Protokół konserwacji')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_sections', to='core.system', verbose_name='System na obiekcie')),
            ],
            options={
                'verbose_name': 'Sekcja protokołu konserwacji',
                'verbose_name_plural': 'Sekcje protokołu konserwacji',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność w sekcji')),
                ('label', models.CharField(help_text="Np. 'Sprawdzenie zasilania centrali'.", max_length=255, verbose_name='Opis czynności')),
                ('result', models.CharField(choices=[('OK', '✓ poprawny'), ('FAIL', 'X niepoprawny'), ('NOT_DONE', 'O niewykonany')], default='NOT_DONE', max_length=16, verbose_name='Wynik')),
                ('note', models.TextField(blank=True, help_text="Dopisek pod punktem, np. 'data montażu: 2025/02'.", verbose_name='Tekst własny')),
                ('active', models.BooleanField(default=True, help_text='Czy ten punkt jest używany dla danego obiektu.', verbose_name='Aktywny')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='core.maintenancesection', verbose_name='Sekcja protokołu')),
            ],
            options={
                'verbose_name': 'Punkt kontrolny przeglądu',
                'verbose_name_plural': 'Punkty kontrolne przeglądu',
                'ordering': ['order', 'id'],
            },
        ),
    ]
