# Generated by Django 5.2.8 on 2025-12-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_maintenanceprotocol_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceprotocol',
            name='number',
            field=models.CharField(blank=True, help_text='Numer w formacie KS {kolejny}/{MM}/{RRRR}.', max_length=50, null=True, verbose_name='Numer protokołu'),
        ),
    ]
