# Generated by Django 5.2.8 on 2025-12-08 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_maintenanceprotocol_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='maintenance_execution_month_in_period',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Dla przeglądów co kwartał: 1–3 (1 = pierwszy miesiąc kwartału itd.). Dla 2x w roku: 1–6. Dla miesięcznych zazwyczaj 1.', null=True, verbose_name='Miesiąc wykonania w okresie'),
        ),
        migrations.AlterField(
            model_name='servicereport',
            name='work_order',
            field=models.OneToOneField(help_text='Zlecenie, którego dotyczy ten protokół (typu Serwis).', on_delete=django.db.models.deletion.CASCADE, related_name='service_report', to='core.workorder', verbose_name='Zlecenie'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.CharField(help_text="Np. 'Awaria domofonu kl. B', 'Konserwacja SSP Q1/2025'.", max_length=255, verbose_name='Tytuł / krótki opis'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('MAINTENANCE', 'Konserwacja'), ('SERVICE', 'Serwis'), ('JOB', 'Montaż'), ('OTHER', 'Inne')], default='SERVICE', max_length=20, verbose_name='Typ zlecenia'),
        ),
    ]
