# Generated by Django 5.2.8 on 2025-12-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_site_maintenance_execution_month_in_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereportitem',
            name='unit',
            field=models.CharField(choices=[('SZT', 'szt.'), ('USL', 'usł.'), ('RBH', 'rbh.'), ('KPL', 'kpl.'), ('INNE', 'inne')], default='RBH', max_length=10, verbose_name='Jm'),
        ),
    ]
