# Generated by Django 5.2.8 on 2025-12-18 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_servicereportitem_unit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('NEW', 'Do umówienia'), ('SCHEDULED', 'Umówione'), ('IN_PROGRESS', 'Realizacja'), ('REALIZED', 'Zrealizowane'), ('WAITING_FOR_DECISION', 'Decyzja'), ('WAITING_FOR_PARTS', 'Materiał'), ('COMPLETED', 'Zakończone'), ('CANCELLED', 'Odwołane')], default='NEW', max_length=32, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='WorkOrderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('STATUS_CHANGE', 'Zmiana statusu')], default='STATUS_CHANGE', max_length=32, verbose_name='Typ zdarzenia')),
                ('old_status', models.CharField(blank=True, max_length=32, verbose_name='Status poprzedni')),
                ('new_status', models.CharField(max_length=32, verbose_name='Status nowy')),
                ('source', models.CharField(default='PORTAL', max_length=16, verbose_name='Źródło')),
                ('is_read', models.BooleanField(default=False, verbose_name='Przeczytane (biuro)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workorder_events', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.workorder', verbose_name='Zlecenie')),
            ],
            options={
                'verbose_name': 'Powiadomienie zlecenia',
                'verbose_name_plural': 'Powiadomienia zleceń',
                'ordering': ['-created_at'],
            },
        ),
    ]
