# Generated by Django 5.2.8 on 2025-12-21 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_workorder_status_workorderevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.entity', verbose_name='Dane fakturowe'),
        ),
    ]
