# Generated by Django 5.2.8 on 2025-12-21 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_site_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='core.site', verbose_name='Obiekt'),
        ),
        migrations.AlterField(
            model_name='maintenanceprotocol',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_protocols', to='core.site', verbose_name='Obiekt'),
        ),
        migrations.AlterField(
            model_name='site',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sites', to='core.entity', verbose_name='Dane fakturowe'),
        ),
        migrations.AlterField(
            model_name='system',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='core.site', verbose_name='Obiekt'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='core.site', verbose_name='Obiekt'),
        ),
    ]
