# Generated by Django 5.2.8 on 2025-12-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_job_site_alter_maintenanceprotocol_site_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['sort_order', 'system_type', 'manufacturer', 'model', 'name'], 'verbose_name': 'System na obiekcie', 'verbose_name_plural': 'Systemy na obiektach'},
        ),
        migrations.AddField(
            model_name='system',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Kolejność'),
        ),
    ]
