# Generated by Django 5.2.8 on 2025-12-22 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_system_options_system_sort_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': 'System na obiekcie', 'verbose_name_plural': 'Systemy na obiektach'},
        ),
    ]
